#!/bin/sh
# postrm script
#
# see: dh_installdeb(1)

set -e

if dpkg-maintscript-helper supports rm_conffile; then
        dpkg-maintscript-helper rm_conffile /etc/init/nmos-reverse-proxy.conf 0.2.0~ nmos-reverse-proxy -- "$@"
fi

#DEBHELPER#

exit 0
